import type { Song } from "../types"

export const pretender: Song = {
  id: "pretender",
  title: "Pretender",
  artist: "Official髭男dism",
  youtubeId: "TQ8WlA2GXbk",
  releaseDate: "2019-04-16",
  duration: "5:36",
  lyrics: [
    {
      timestamp: "0:31",
      original: "君とのラブストーリー それは予想通り",
      hiragana: "きみとのラブストーリー それはよそうどおり",
      katakana: "キミトノラブストーリー ソレハヨソウドオリ",
      korean: "너와의 러브 스토리, 그것은 예상대로",
    },
    {
      timestamp: "0:37",
      original: "いざ始まればひとり芝居だ",
      hiragana: "いざはじまればひとりしばいだ",
      katakana: "イザハジマレバヒトリシバイダ",
      korean: "막상 시작되면 혼자만의 연극이야",
    },
    {
      timestamp: "0:41",
      original: "ずっとそばにいたって 結局ただの観客だ",
      hiragana: "ずっとそばにいたって けっきょくただのかんきゃくだ",
      katakana: "ズットソバニイタッテ ケッキョクタダノカンキャクダ",
      korean: "계속 곁에 있어도 결국 그저 관객일 뿐이야",
    },
    {
      timestamp: "0:47",
      original: "感情のないアイムソーリー それはいつも通り",
      hiragana: "かんじょうのないあいむそりー それはいつもどおり",
      katakana: "カンジョウノナイアイムソーリー ソレハイツモドオリ",
      korean: "감정 없는 I'm sorry, 그것은 늘 그렇듯이",
    },
    {
      timestamp: "0:53",
      original: "慣れてしまえば悪くはないけど",
      hiragana: "なれてしまえばわるくはないけど",
      katakana: "ナレテシマエバワルクハナイケド",
      korean: "익숙해지면 나쁘지 않지만",
    },
    {
      timestamp: "0:57",
      original: "君とのロマンスは人生柄 続きはしないことを知った",
      hiragana: "きみとのろまんすはじんせい柄 つづきはしないことをしった",
      katakana: "キミトノロマンスハジンセイガラ ツヅキハシナイコトヲシッタ",
      korean: "너와의 로맨스는 인생의 무늬, 계속되지 않을 걸 알았어",
    },
    {
      timestamp: "1:08",
      original: "もっと違う設定で もっと違う関係で",
      hiragana: "もっとちがうせっていで もっとちがうかんけいで",
      katakana: "モットチガウセッテイデ モットチガウカンケイデ",
      korean: "조금 다른 설정으로 조금 다른 관계로",
    },
    {
      timestamp: "1:12",
      original: "出会える世界線 選べたらよかった",
      hiragana: "であえるせかいせん えらべたらよかった",
      katakana: "デアエルセカイセン エラベタラヨカッタ",
      korean: "만날 수 있는 세계선이었으면 좋았을 텐데",
    },
    {
      timestamp: "1:18",
      original: "もっと違う性格で もっと違う価値観で",
      hiragana: "もっとちがうせいかくで もっとちがうかちかん で",
      katakana: "モットチガウセイカクデ モットチガウカチカンデ",
      korean: "조금 다른 성격으로 조금 다른 가치관으로",
    },
    {
      timestamp: "1:23",
      original: "愛を伝えられたらいいな",
      hiragana: "あいを つたえられたらいいな",
      katakana: "アイヲツタエラレタライイナ",
      korean: "사랑을 전할 수 있었으면 좋겠어",
    },
    {
      timestamp: "1:28",
      original: "そう願っても無駄だから",
      hiragana: "そうねがってもむだだから",
      katakana: "ソウネガッテモムダダカラ",
      korean: "그렇게 바라도 헛수고야",
    },
    { timestamp: "1:33", original: "グッバイ", hiragana: "ぐっばい", katakana: "グッバイ", korean: "굿바이" },
    {
      timestamp: "1:34",
      original: "君の運命のヒトは僕じゃない",
      hiragana: "きみのうんめいのひとはぼくじゃない",
      katakana: "キミノウンメイノヒトハボクジャナイ",
      korean: "너의 운명의 사람은 내가 아니야",
    },
    {
      timestamp: "1:39",
      original: "辛いけど否めない でも離れ難いのさ",
      hiragana: "つらいけどうなめない でもはなれがたいのさ",
      katakana: "ツライケドウナメナイ デモハナレガタイノサ",
      korean: "괴로워도 부정할 수 없어, 하지만 떠나기 어려워",
    },
    {
      timestamp: "1:45",
      original: "その髪に触れただけで 痛いや いやでも",
      hiragana: "そのかみにふれただけで いたいや いやでも",
      katakana: "ソノカミニフレタダケデ イタイヤ イヤデモ",
      korean: "그 머리카락에 닿기만 해도 아프구나, 하지만",
    },
    {
      timestamp: "1:52",
      original: "甘いな　いやいや",
      hiragana: "あまいな いやいや",
      katakana: "アマイナ イヤイヤ",
      korean: "달콤하네, 아니 아니",
    },
    { timestamp: "1:54", original: "グッバイ", hiragana: "ぐっばい", katakana: "グッバイ", korean: "굿바이" },
    {
      timestamp: "1:55",
      original: "それじゃ僕にとって君は何？",
      hiragana: "それじゃぼくにとってきみはなに？",
      katakana: "ソレジャボクニトッテキミハナニ？",
      korean: "그럼 나에게 너는 뭐야?",
    },
    {
      timestamp: "2:00",
      original: "答えは分からない 分かりたくもないのさ",
      hiragana: "こたえはわからない わかりたくもないのさ",
      katakana: "コタエハワカラナイ ワカリタクモナイノサ",
      korean: "답은 모르겠어, 알고 싶지도 않아",
    },
    {
      timestamp: "2:06",
      original: "たったひとつ確かなことがあるとするのならば",
      hiragana: "たったひとつたしかなことがあるとするのならば",
      katakana: "タッタヒトツタシカナコトガアルトスルノナラバ",
      korean: "확실한 게 하나 있다면",
    },
    {
      timestamp: "2:14",
      original: "「君は綺麗だ」",
      hiragana: "「きみはきれいだ」",
      katakana: "「キミハキレイダ」",
      korean: "「너는 아름다워」",
    },
    {
      timestamp: "2:21",
      original: "誰かが偉そうに 語る恋愛の論理",
      hiragana: "だれかがえらそうに かたるれんあいのろんり",
      katakana: "ダレカガエラソウニ カタルレンアイノロンリ",
      korean: "누군가 잘난 척 연애의 논리를 말해도",
    },
    {
      timestamp: "2:27",
      original: "何ひとつとしてピンとこなくて",
      hiragana: "なにひとつとしてぴんとこなくて",
      katakana: "ナニヒトツトシテピントコナクテ",
      korean: "아무것도 와닿지 않아",
    },
    {
      timestamp: "2:31",
      original: "飛行機の窓から見下ろした 知らない街の夜景みたいだ",
      hiragana: "ひこうきのまどからみおろした しらないまちのやけいみたいだ",
      katakana: "ヒコウキノマドカラミオロシタ シラナイマチノヤケイミタイダ",
      korean: "비행기 창문으로 내려다본 낯선 도시의 야경 같아",
    },
    {
      timestamp: "2:41",
      original: "もっと違う設定で もっと違う関係で",
      hiragana: "もっとちがうせっていで もっとちがうかんけいで",
      katakana: "モットチガウセッテイデ モットチガウカンケイデ",
      korean: "조금 다른 설정으로 조금 다른 관계로",
    },
    {
      timestamp: "2:47",
      original: "出会える世界線 選べたらよかった",
      hiragana: "であえるせかいせん えらべたらよかった",
      katakana: "デアエルセカイセン エラベタラヨカッタ",
      korean: "만날 수 있는 세계선이었으면 좋았을 텐데",
    },
    {
      timestamp: "2:52",
      original: "いたって純な心で 叶った恋を抱きしめて",
      hiragana: "いたってじゅんなこころで かなったこいをだきしめて",
      katakana: "イタッテジュンナココロデ カナッタコイヲダキシメテ",
      korean: "아주 순수한 마음으로 이루어진 사랑을 안고",
    },
    {
      timestamp: "2:57",
      original: "「好きだ」とか無責任に言えたらいいな",
      hiragana: "「すきだ」とかなんぱくせきにいえたらいいな",
      katakana: "「スキダ」とカナンシンニイエタライイナ",
      korean: "'좋아'라고 무책임하게 말할 수 있었으면 좋겠어",
    },
    {
      timestamp: "3:02",
      original: "そう願っても虚しいのさ",
      hiragana: "そうねがってもうつしいのさ",
      katakana: "ソウネガッテモウツシイノサ",
      korean: "그렇게 바라도 공허해",
    },
    { timestamp: "3:07", original: "グッバイ", hiragana: "ぐっばい", katakana: "グッバイ", korean: "굿바이" },
    {
      timestamp: "3:08",
      original: "繋いだ手の向こうにエンドライン",
      hiragana: "つないだてのむこうにえんどらいん",
      katakana: "ツナイダテノムコウニエンドライン",
      korean: "잡은 손 너머에 엔드라인",
    },
    {
      timestamp: "3:13",
      original: "引き伸ばすたびに 疼きだす未来には",
      hiragana: "ひきのばすたびに うずきだすみらいには",
      katakana: "ヒキノバスタビニ ウズキダスミライニハ",
      korean: "끌어당길 때마다 욱신거리는 미래에는",
    },
    {
      timestamp: "3:19",
      original: "君はいない その事実にCry...",
      hiragana: "きみはいない そのじじつにCry...",
      katakana: "キミハイナイ ソノジジツニクライ...",
      korean: "너는 없어, 그 사실에 울어...",
    },
    {
      timestamp: "3:27",
      original: "そりゃ苦しいよな",
      hiragana: "そりゃくるしいよな",
      katakana: "ソリャクルシイヨナ",
      korean: "그야 괴로울 만하지",
    },
    { timestamp: "3:49", original: "グッバイ", hiragana: "ぐっばい", katakana: "グッバイ", korean: "굿바이" },
    {
      timestamp: "3:50",
      original: "君の運命のヒトは僕じゃない",
      hiragana: "きみのうんめいのひとはぼくじゃない",
      katakana: "キミノウンメイノヒトハボクジャナイ",
      korean: "너의 운명의 사람은 내가 아니야",
    },
    {
      timestamp: "3:54",
      original: "辛いけど否めない でも離れ難いのさ",
      hiragana: "つらいけどうなめない でもはなれがたいのさ",
      katakana: "ツライケドウナメナイ デモハナレガタイノサ",
      korean: "괴로워도 부정할 수 없어, 하지만 떠나기 어려워",
    },
    {
      timestamp: "4:01",
      original: "その髪に触れただけで 痛いや いやでも",
      hiragana: "そのかみにふれただけで いたいや いやでも",
      katakana: "ソノカミニフレタダケデ イタイヤ イヤデモ",
      korean: "그 머리카락에 닿기만 해도 아프구나, 하지만",
    },
    {
      timestamp: "4:07",
      original: "甘いな いやいや",
      hiragana: "あまいな いやいや",
      katakana: "アマイナ イヤイヤ",
      korean: "달콤하네, 아니 아니",
    },
    { timestamp: "4:09", original: "グッバイ", hiragana: "ぐっばい", katakana: "グッバイ", korean: "굿바이" },
    {
      timestamp: "4:10",
      original: "それじゃ僕にとって君は何？",
      hiragana: "それじゃぼくにとってきみはなに？",
      katakana: "ソレジャボクニトッテキミハナニ？",
      korean: "그럼 나에게 너는 뭐야?",
    },
    {
      timestamp: "4:15",
      original: "答えは分からない 分かりたくもないのさ",
      hiragana: "こたえはわからない わかりたくもないのさ",
      katakana: "コタエハワカラナイ ワカリタクモナイノサ",
      korean: "답은 모르겠어, 알고 싶지도 않아",
    },
    {
      timestamp: "4:21",
      original: "たったひとつ確かなことがあるとするのならば",
      hiragana: "たったひとつたしかなことがあるとするのならば",
      katakana: "タッタヒトツタシカナコトガアルトスルノナラバ",
      korean: "확실한 게 하나 있다면",
    },
    {
      timestamp: "4:29",
      original: "「君は綺麗だ」",
      hiragana: "「きみはきれいだ」",
      katakana: "「キミハキレイダ」",
      korean: "「너는 아름다워」",
    },
    {
      timestamp: "4:32",
      original: "それもこれもロマンスの定めなら 悪くないよな",
      hiragana: "それもこれもろまんすのさだめなら わるくないよな",
      katakana: "ソレモコレモロマンスノサダメナラ ワルクナイヨナ",
      korean: "이것도 저것도 로맨스의 숙명이라면 나쁘지 않아",
    },
    {
      timestamp: "4:42",
      original: "永遠も約束もないけれど",
      hiragana: "えいえんもやくそくもないけれど",
      katakana: "エイエンもヤクソクモナイケレド",
      korean: "영원도 약속은 없지만",
    },
    {
      timestamp: "4:50",
      original: "「とても綺麗だ」",
      hiragana: "「とてもきれいだ」",
      katakana: "「トテモキレイダ」",
      korean: "「너는 아주 아름다워」",
    },
  ],
}

