import type { Song } from "../types"

export const kaijuNoHanauta: Song = {
  id: "kaiju-no-hanauta",
  title: "怪獣の花唄",
  artist: "Vaundy",
  youtubeId: "t4vh3OjYWHk",
  releaseDate: "2020-05-27",
  duration: "3:44",
  lyrics: [
    {
      timestamp: "0:14",
      original: "思い出すのは君の歌",
      hiragana: "おもいだすのはきみのうた",
      katakana: "オモイダスノハキミノウタ",
      korean: "생각나는 것은 너의 노래",
    },
    {
      timestamp: "0:20",
      original: "会いたくなるのは僕の歌",
      hiragana: "あいたくなるのはぼくのうた",
      katakana: "アイタクナルノハボクノウタ",
      korean: "만나고 싶어지는 것은 나의 노래",
    },
    {
      timestamp: "0:26",
      original: "歌い継がれるのは誰の歌",
      hiragana: "うたいつがれるのはだれのうた",
      katakana: "ウタイツガレルノハダレノウタ",
      korean: "노래로 이어지는 것은 누구의 노래",
    },
    {
      timestamp: "0:32",
      original: "書き換えられるのは夢の歌",
      hiragana: "かきかえられるのはゆめのうた",
      katakana: "カキカエラレルノハユメノウタ",
      korean: "다시 쓰이는 것은 꿈의 노래",
    },
    {
      timestamp: "0:38",
      original: "思い出したんだ 君の歌",
      hiragana: "おもいだしたんだ きみのうた",
      katakana: "オモイダシタンダ キミノウタ",
      korean: "떠올랐어 너의 노래",
    },
    {
      timestamp: "0:45",
      original: "口ずさむのは僕の歌",
      hiragana: "くちずさむのはぼくのうた",
      katakana: "クチズサムノハボクノウタ",
      korean: "흥얼거리는 것은 나의 노래",
    },
    {
      timestamp: "0:51",
      original: "誰も知らない怪獣の 輝いたあとの歌",
      hiragana: "だれもしらないかいじゅうの かがやいたあとのうた",
      katakana: "ダレモシラナイカイジュウノ カガヤイタアトノウタ",
      korean: "아무도 모르는 괴물의 빛나고 난 뒤의 노래",
    },
    {
      timestamp: "1:03",
      original: "ねえ、僕ら",
      hiragana: "ねえ、ぼくら",
      katakana: "ネエ、ボクラ",
      korean: "있지, 우리들",
    },
    {
      timestamp: "1:06",
      original: "何回だってさ 何回だってさ",
      hiragana: "なんかいだってさ なんかいだってさ",
      katakana: "ナンカイダッテサ ナンカイダッテサ",
      korean: "몇 번이라도 말야 몇 번이라도 말야",
    },
    {
      timestamp: "1:09",
      original: "思い出したくなるよな",
      hiragana: "おもいだしたくなるよな",
      katakana: "オモイダシタクナルヨナ",
      korean: "다시 떠올리고 싶어지잖아",
    },
    {
      timestamp: "1:13",
      original: "3000年先の未来でも",
      hiragana: "さんぜんねんさきのみらいでも",
      katakana: "サンゼンネンサキノミライデモ",
      korean: "3000년 후의 미래에서도",
    },
    {
      timestamp: "1:16",
      original: "何回だってさ 何回だってさ",
      hiragana: "なんかいだってさ なんかいだってさ",
      katakana: "ナンカイダッテサ ナンカイダッテサ",
      korean: "몇 번이라도 말야 몇 번이라도 말야",
    },
    {
      timestamp: "1:19",
      original: "歌い継いでしまうよな",
      hiragana: "うたいついでしまうよな",
      katakana: "ウタイツイデシマウヨナ",
      korean: "계속해서 노래해 버리잖아",
    },
    {
      timestamp: "1:25",
      original: "僕らの歌を",
      hiragana: "ぼくらのうたを",
      katakana: "ボクラノウタヲ",
      korean: "우리들의 노래를",
    },
    {
      timestamp: "1:52",
      original: "もっと前で見せてくれよ",
      hiragana: "もっとまえでみせてくれよ",
      katakana: "モットマエデミセテクレヨ",
      korean: "좀 더 앞에서 보여달라고",
    },
    {
      timestamp: "1:58",
      original: "もっと横で笑ってくれよ",
      hiragana: "もっとよこでわらってくれよ",
      katakana: "モットヨコデワラッテクレヨ",
      korean: "좀 더 곁에서 웃어달라고",
    },
    {
      timestamp: "2:04",
      original: "誰も知らない怪獣の 輝いたあとの歌",
      hiragana: "だれもしらないかいじゅうの かがやいたあとのうた",
      katakana: "ダレモシラナイカイジュウノ カガヤイタアトノウタ",
      korean: "아무도 모르는 괴물의 빛나고 난 뒤의 노래",
    },
    {
      timestamp: "2:16",
      original: "ねえ、僕ら",
      hiragana: "ねえ、ぼくら",
      katakana: "ネエ、ボクラ",
      korean: "있지, 우리들",
    },
    {
      timestamp: "2:19",
      original: "何回だってさ 何回だってさ",
      hiragana: "なんかいだってさ なんかいだってさ",
      katakana: "ナンカイダッテサ ナンカイダッテサ",
      korean: "몇 번이라도 말야 몇 번이라도 말야",
    },
    {
      timestamp: "2:22",
      original: "思い出したくなるよな",
      hiragana: "おもいだしたくなるよな",
      katakana: "オモイダシタクナルヨナ",
      korean: "다시 떠올리고 싶어지잖아",
    },
    {
      timestamp: "2:25",
      original: "3000年先の未来でも",
      hiragana: "さんぜんねんさきのみらいでも",
      katakana: "サンゼンネンサキノミライデモ",
      korean: "3000년 후의 미래에서도",
    },
    {
      timestamp: "2:28",
      original: "何回だってさ 何回だってさ",
      hiragana: "なんかいだってさ なんかいだってさ",
      katakana: "ナンカイダッテサ ナンカイダッテサ",
      korean: "몇 번이라도 말야 몇 번이라도 말야",
    },
    {
      timestamp: "2:32",
      original: "歌い継いでしまうよな",
      hiragana: "うたいついでしまうよな",
      katakana: "ウタイツイデシマウヨナ",
      korean: "계속해서 노래해 버리잖아",
    },
    {
      timestamp: "2:37",
      original: "僕らの歌を",
      hiragana: "ぼくらのうたを",
      katakana: "ボクラノウタヲ",
      korean: "우리들의 노래를",
    },
    {
      timestamp: "2:53",
      original: "落ちていく日々を 忘れてしまうまえに",
      hiragana: "おちていくひびを わすれてしまうまえに",
      katakana: "オチテイクヒビヲ ワスレテシマウマエニ",
      korean: "떨어져가는 나날들을 잊어버리기 전에",
    },
    {
      timestamp: "3:04",
      original: "ねえ、僕ら",
      hiragana: "ねえ、ぼくら",
      katakana: "ネエ、ボクラ",
      korean: "있지, 우리들",
    },
    {
      timestamp: "3:07",
      original: "何回だってさ 何回だってさ",
      hiragana: "なんかいだってさ なんかいだってさ",
      katakana: "ナンカイダッテサ ナンカイダッテサ",
      korean: "몇 번이라도 말야 몇 번이라도 말야",
    },
    {
      timestamp: "3:10",
      original: "思い出したくなるよな",
      hiragana: "おもいだしたくなるよな",
      katakana: "オモイダシタクナルヨナ",
      korean: "다시 떠올리고 싶어지잖아",
    },
    {
      timestamp: "3:13",
      original: "3000年先の未来でも",
      hiragana: "さんぜんねんさきのみらいでも",
      katakana: "サンゼンネンサキノミライデモ",
      korean: "3000년 후의 미래에서도",
    },
    {
      timestamp: "3:16",
      original: "何回だってさ 何回だってさ",
      hiragana: "なんかいだってさ なんかいだってさ",
      katakana: "ナンカイダッテサ ナンカイダッテサ",
      korean: "몇 번이라도 말야 몇 번이라도 말야",
    },
    {
      timestamp: "3:19",
      original: "歌い継いでしまうよな",
      hiragana: "うたいついでしまうよな",
      katakana: "ウタイツイデシマウヨナ",
      korean: "계속해서 노래해 버리잖아",
    },
    {
      timestamp: "3:25",
      original: "僕らの歌を",
      hiragana: "ぼくらのうたを",
      katakana: "ボクラノウタヲ",
      korean: "우리들의 노래를",
    },
  ],
}

