import type { Song } from "../types"

export const irisOut: Song = {
  id: "iris-out-yonezu-kenshi",
  title: "IRIS OUT",
  artist: "米津玄師",
  youtubeId: "LmZD-TU96q4",
  thumbnail: "https://img.youtube.com/vi/LmZD-TU96q4/maxresdefault.jpg",
  releaseDate: "2024-08-08",
  duration: "2:34",
  lyrics: [
    {
      timestamp: "0:18",
      original: "駄目駄目駄目",
      hiragana: "だめだめだめ",
      katakana: "ダメダメダメ",
      korean: "안 돼 안 돼 안 돼",
    },
    {
      timestamp: "0:19",
      original: "脳みその中から「やめろ馬鹿」と喚くモラリティ",
      hiragana: "のうみそのなかから「やめろばか」とわめくもらりてぃ",
      katakana: "ノウミソノナカカラ「ヤメロバカ」トワメクモラリティ",
      korean: "뇌 속에서 「그만둬 바보야」라고 아우성치는 도덕성",
    },
    {
      timestamp: "0:25",
      original: "ダーリンベイビーダーリン",
      hiragana: "だーりんべいびーだーりん",
      katakana: "ダーリンベイビーダーリン",
      korean: "다링 베이비 다링",
    },
    {
      timestamp: "0:27",
      original: "半端なくラブ！ときらめき浮き足立つフィロソフィ",
      hiragana: "はんぱなくらぶ！ときらめきうきあしたつふぃろそふぃ",
      katakana: "ハンパナクラブ！トキラメキウキアシタツフィロソフィ",
      korean: "장난 아니게 러브! 하며 반짝이며 들떠버리는 철학",
    },
    {
      timestamp: "0:32",
      original: "死ぬほど可愛い上目遣い",
      hiragana: "しぬほどかわいいうえめづかい",
      katakana: "シヌホドカワイイウエメヅカイ",
      korean: "죽을 만큼 귀여운 치켜뜬 눈",
    },
    {
      timestamp: "0:33",
      original: "なにがし法に触れるくらい",
      hiragana: "なにがしほうにふれるくらい",
      katakana: "ナニガシホウニフレルクライ",
      korean: "무슨 법에 저촉될 정도로",
    },
    {
      timestamp: "0:35",
      original: "ばら撒く乱心",
      hiragana: "ばらまくらんしん",
      katakana: "バラマクランシン",
      korean: "흩뿌려지는 난심",
    },
    {
      timestamp: "0:36",
      original: "気づけば蕩尽",
      hiragana: "きづけばとうじん",
      katakana: "キヅケバトウジン",
      korean: "어느샌가 탕진",
    },
    {
      timestamp: "0:37",
      original: "この世に生まれた君が悪い",
      hiragana: "このよにうまれたきみがわるい",
      katakana: "コノヨニウマレタキミガワルイ",
      korean: "이 세상에 태어난 네가 나빠",
    },
    {
      timestamp: "0:39",
      original: "やたらとしんどい恋煩い",
      hiragana: "やたらとしんどいこいわずらい",
      katakana: "ヤタラトシンドイコイワズライ",
      korean: "지나치게 힘든 상사병",
    },
    {
      timestamp: "0:40",
      original: "バラバラんなる頭とこの身体",
      hiragana: "ばらばらんなるあたまとこのからだ",
      katakana: "バラバランナルアタマトコノカラダ",
      korean: "조각조각 나는 머리와 이 몸",
    },
    {
      timestamp: "0:42",
      original: "頸動脈からアイラブユーが噴き出て",
      hiragana: "けいどうみゃくからあいらぶゆーがふきでて",
      katakana: "ケイドウミャクカラアイラブユーガフキデテ",
      korean: "경동맥에서 아이 러브 유가 뿜어져 나오며",
    },
    {
      timestamp: "0:45",
      original: "アイリスアウト",
      hiragana: "あいりすあうと",
      katakana: "アイリスアウト",
      korean: "아이리스 아웃",
    },
    {
      timestamp: "0:46",
      original: "一体どうしようこの想いを",
      hiragana: "いったいどうしようこのおもいを",
      katakana: "イッタイドウシヨウコノオモイオ",
      korean: "도대체 어쩌지 이 마음을",
    },
    {
      timestamp: "0:48",
      original: "どうしようあばらの奥を",
      hiragana: "どうしようあばらのおくを",
      katakana: "ドウシヨウアバラノオクヲ",
      korean: "어쩌지 갈비뼈 안쪽을",
    },
    {
      timestamp: "0:50",
      original: "ザラメが溶けてゲロになりそう",
      hiragana: "ざらめがとけてげろになりそう",
      katakana: "ザラメガトケテゲロニナリソウ",
      korean: "설탕이 녹아 구토가 나올 것 같아",
    },
    {
      timestamp: "0:53",
      original: "瞳孔バチ開いて溺れ死にそう",
      hiragana: "どうこうばちひらいておぼれしにそう",
      katakana: "ドウコウバチヒライテオボレシニソウ",
      korean: "동공이 번쩍 뜨여 익사할 것 같아",
    },
    {
      timestamp: "0:57",
      original: "今この世で君だけ大正解",
      hiragana: "いまこのよできみだけだいせいかい",
      katakana: "イマコノヨデキミダケダイセイカイ",
      korean: "지금 이 세상에서 너만이 정답",
    },
    {
      timestamp: "1:14",
      original: "ひっくり返っても勝ちようない",
      hiragana: "ひっくりかえってもかちようない",
      katakana: "ヒックリカエッテモカチヨウナイ",
      korean: "뒤집어져도 이길 방법이 없어",
    },
    {
      timestamp: "1:16",
      original: "君だけルールは適用外",
      hiragana: "きみだけるーるはてきようがい",
      katakana: "キミダケルールハテキヨウガイ",
      korean: "너만은 규칙 적용 제외",
    },
    {
      timestamp: "1:18",
      original: "四つともオセロは黒しかない",
      hiragana: "よっつともおせろはくろしかない",
      katakana: "ヨッツトモオセロハクロシカナイ",
      korean: "네 군데 다 오셀로는 검은색뿐",
    },
    {
      timestamp: "1:19",
      original: "カツアゲ放題",
      hiragana: "かつあげほうだい",
      katakana: "カツアゲホウダイ",
      korean: "마음껏 뜯기는 중",
    },
    {
      timestamp: "1:21",
      original: "君が笑顔で放ったアバダケダブラ",
      hiragana: "きみがえがおではなったあばだけだぶら",
      katakana: "キミガエガオデハナッタアバダケダブラ",
      korean: "네가 웃으며 쏜 아바다 케다브라",
    },
    {
      timestamp: "1:24",
      original: "デコにスティグマ　申し訳ねえな",
      hiragana: "でこにすてぃぐま　もうしわけねえな",
      katakana: "デコニスティグマ　モウシワケネエナ",
      korean: "이마에 스티그마, 미안하게 됐네",
    },
    {
      timestamp: "1:26",
      original: "矢を刺して 貫いて ここ弱点",
      hiragana: "やをさして つらぬいて ここじゃくてん",
      katakana: "ヤヲサシテ ツラヌイテ ココジャクテン",
      korean: "화살을 꽂고 꿰뚫어 줘, 여기가 약점",
    },
    {
      timestamp: "1:29",
      original: "死ぬほど可愛い上目遣い",
      hiragana: "しぬほどかわいいうえめづかい",
      katakana: "シヌホドカワイイウエメヅカイ",
      korean: "죽을 만큼 귀여운 치켜뜬 눈",
    },
    {
      timestamp: "1:36",
      original: "パチモンでもいい何でもいい",
      hiragana: "ぱちもんでもいいなんでもいい",
      katakana: "パチモンデモイイナンデモイイ",
      korean: "짝퉁이라도 좋아 뭐든 좋아",
    },
    {
      timestamp: "1:37",
      original: "今君と名付いてる全て欲しい",
      hiragana: "いまきみとなづいてるすべてほしい",
      katakana: "イマキミトナヅイテルスベテホシイ",
      korean: "지금 너라고 이름 붙은 모든 걸 갖고 싶어",
    },
    {
      timestamp: "1:39",
      original: "頸動脈からアイラブユーが噴き出て",
      hiragana: "けいどうみゃくからあいらぶゆーがふきでて",
      katakana: "ケイドウミャクカラアイラブユーガフキデテ",
      korean: "경동맥에서 아이 러브 유가 뿜어져 나오며",
    },
    {
      timestamp: "1:57",
      original: "一体どうしようこの想いを",
      hiragana: "いったいどうしようこのおもいを",
      katakana: "イッタイドウシヨウコノオモイオ",
      korean: "도대체 어쩌지 이 마음을",
    },
    {
      timestamp: "2:08",
      original: "今この世で君だけ大正解",
      hiragana: "いまこのよできみだけだいせいかい",
      katakana: "イマコノヨデキミダケダイセイカイ",
      korean: "지금 이 세상에서 너만이 정답",
    },
  ],
}

