import type { Song } from "../types"

export const lemon: Song = {
  id: "lemon-yonezu-kenshi",
  title: "Lemon",
  artist: "米津玄師",
  youtubeId: "SX_ViT4Ra7k",
  thumbnail: "https://img.youtube.com/vi/SX_ViT4Ra7k/maxresdefault.jpg",
  releaseDate: "2018-02-12",
  duration: "4:35",
  lyrics: [
    {
      timestamp: "0:02",
      original: "夢ならばどれほどよかったでしょう",
      hiragana: "ゆめならばどれほどよかったでしょう",
      katakana: "ユメラバドレホドヨカッタデショウ",
      korean: "꿈이라면 얼마나 좋았을까요",
    },
    {
      timestamp: "0:07",
      original: "未だにあなたのことを夢にみる",
      hiragana: "いまだにあなたのことをゆめにみる",
      katakana: "イマダニアナタノコトヲユメニミル",
      korean: "아직껏 당신이 나오는 꿈을 꿔",
    },
    {
      timestamp: "0:13",
      original: "忘れた物を取りに帰るように",
      hiragana: "わすれたものをとりにかえるように",
      katakana: "ワスレタモノヲトリニカエルヨウニ",
      korean: "잃어버린 것을 되찾으러 돌아가듯이",
    },
    {
      timestamp: "0:18",
      original: "古びた思い出の埃を払う",
      hiragana: "ふるびたおもいでのほこりをはらう",
      katakana: "フルビタオモイデノホコリヲハラウ",
      korean: "낡은 추억의 먼지를 털어내",
    },
    {
      timestamp: "0:27",
      original: "戻らない幸せがあることを",
      hiragana: "もどらないしあわせがあることを",
      katakana: "モドラナイシアワセガアルコトヲ",
      korean: "돌아올 수 없는 행복이 있다는 것을",
    },
    {
      timestamp: "0:32",
      original: "最後にあなたが教えてくれた",
      hiragana: "さいごにあなたがおしえてくれた",
      katakana: "サイゴニアナタガオシエテクレタ",
      korean: "마지막으로 당신이 알려주었어",
    },
    {
      timestamp: "0:38",
      original: "言えずに隠した昏い過去も",
      hiragana: "いえずにかくしたくらいかこも",
      katakana: "イエズニカクシタクライカコモ",
      korean: "말하지 못하고 숨겼던 어두운 과거도",
    },
    {
      timestamp: "0:43",
      original: "あなたがいなきゃ永遠に昏いまま",
      hiragana: "あなたがいなきゃえいえんにくらいまま",
      katakana: "アナタガイナキャエイエンニクライママ",
      korean: "당신이 있지 않으면 영원히 어두운 채",
    },
    {
      timestamp: "0:49",
      original: "きっともうこれ以上　傷つくことなど",
      hiragana: "きっともうこれいじょう　きずつくことなど",
      katakana: "キットモウコレイジョウ　キズツクコトナド",
      korean: "분명 이제 더 이상 상처입는 일 따위",
    },
    {
      timestamp: "0:55",
      original: "ありはしないとわかっている",
      hiragana: "ありはしないとわかっている",
      katakana: "アリハシナイトワカッテイル",
      korean: "있을 리 없다는 걸 알고 있어",
    },
    {
      timestamp: "1:00",
      original: "あの日の悲しみさえ　あの日の苦しみさえ",
      hiragana: "あのひのかなしみさえ　あのひのくるしみさえ",
      katakana: "アノヒノカナシミサエ　アノヒノクルシミサエ",
      korean: "그 날의 슬픔조차 그 날의 괴로움조차",
    },
    {
      timestamp: "1:05",
      original: "そのすべてを愛してた　あなたとともに",
      hiragana: "そのすべてをあいしてた　あなたとともに",
      katakana: "ソノスベテヲアイシテタ　アナタトトモニ",
      korean: "그 모든 것을 사랑했던 당신과 함께",
    },
    {
      timestamp: "1:10",
      original: "胸に残り離れない　苦いレモンの匂い",
      hiragana: "むねにのこりはなれない　にがいれもんのにおい",
      katakana: "ムネニノコリハナレナイ　ニガイレモンノニオイ",
      korean: "가슴에 남아 떠나지 않는 씁쓸한 레몬 향기",
    },
    {
      timestamp: "1:17",
      original: "雨が降り止むまでは帰れない",
      hiragana: "あめがふりやむまではかえれない",
      katakana: "アメガフリヤムマデハカエレナイ",
      korean: "비가 그치기 전까지는 돌아갈 수 없어",
    },
    {
      timestamp: "1:22",
      original: "今でもあなたはわたしの光",
      hiragana: "いまでもあなたはわたしのひかり",
      katakana: "イマデモアナタハワタシノヒカリ",
      korean: "지금도 당신은 나의 빛",
    },
    {
      timestamp: "1:39",
      original: "暗闇であなたの背をなぞる",
      hiragana: "くらやみであなたのせをなぞる",
      katakana: "クラヤミデアナタノセヲナゾル",
      korean: "어둠 속에서 당신의 뒷모습을 덧그려",
    },
    {
      timestamp: "1:44",
      original: "その輪郭を鮮明に覚えている",
      hiragana: "そのりんかくをせんめいにおぼえている",
      katakana: "ソノリンカクヲセンメイニオボエテイル",
      korean: "그 윤곽을 선명하게 기억하고 있어",
    },
    {
      timestamp: "1:49",
      original: "受け止めきれないものと出会うたび",
      hiragana: "うけとめきれないものとであうたび",
      katakana: "ウケトメキレナイモノトデアウタビ",
      korean: "받아들일 수 없는 것과 만날 때마다",
    },
    {
      timestamp: "1:54",
      original: "溢れて止まないのは涙だけ",
      hiragana: "あふれてやまないのはなみだだけ",
      katakana: "アフレテヤマナイノハナミダダケ",
      korean: "흘러넘쳐 멈추지 않는 것은 눈물 뿐",
    },
    {
      timestamp: "2:01",
      original: "何をしていたの　何を見ていたの",
      hiragana: "なにをしていたの　なにをみていたの",
      katakana: "ナニヲシテイタノ　ナニヲミテイタノ",
      korean: "무엇을 했었나 무엇을 보았었나",
    },
    {
      timestamp: "2:06",
      original: "わたしの知らない横顔で",
      hiragana: "わたしのしらないよこがおで",
      katakana: "ワタシノシラナイヨコガオデ",
      korean: "내가 모르는 옆 얼굴로",
    },
    {
      timestamp: "2:11",
      original: "どこかであなたが今　わたしと同じような",
      hiragana: "どこかであなたがいま　わたしとおなじような",
      katakana: "ドコカデアナタイマ　ワタシトオナジヨウナ",
      korean: "어디선가 당신이 지금 나와 같은",
    },
    {
      timestamp: "2:17",
      original: "涙にくれ寂しさの中にいるなら",
      hiragana: "なみだにくれさびしさのなかにいるなら",
      katakana: "ナミダニクレサビシサノナカニイルナラ",
      korean: "눈물이 주는 쓸쓸함 속에 있다면",
    },
    {
      timestamp: "2:22",
      original: "わたしのことなどどうか忘れてください",
      hiragana: "わたしのことなどどうかわすれてください",
      katakana: "ワタシノコトナドドウカワスレテクダサイ",
      korean: "나 같은 것 따위 부디 잊어주세요",
    },
    {
      timestamp: "2:28",
      original: "そんなことを心から願うほどに",
      hiragana: "そんなことをこころからねがうほどに",
      katakana: "ソンナコトヲココロカラネガウホドニ",
      korean: "그런 것을 진심으로 바랄 정도로",
    },
    {
      timestamp: "2:34",
      original: "今でもあなたはわたしの光",
      hiragana: "いまでもあなたはわたしのひかり",
      katakana: "イマデモアナタハワタシノヒカリ",
      korean: "지금도 당신은 나의 빛",
    },
    {
      timestamp: "2:43",
      original: "自分が思うより　恋をしていたあなたに",
      hiragana: "じぶんがおもうより　こいをしていたあなたに",
      katakana: "ジブンガオモウヨリ　コイヲシテイタアナタニ",
      korean: "내 생각보다 더 사랑을 하고 있었던 당신에게",
    },
    {
      timestamp: "2:54",
      original: "あれから思うように　息ができない",
      hiragana: "あれからおもうように　いきができない",
      katakana: "アレカラオモウヨウニ　イキガデキナイ",
      korean: "그 뒤로 생각하는 대로 숨을 쉴 수 없어",
    },
    {
      timestamp: "3:05",
      original: "あんなに側にいたのに　まるで嘘みたい",
      hiragana: "あんなにそばにいたのに　まるでうそみたい",
      katakana: "アンナニソバニイタノニ　マルデウソミタイ",
      korean: "그렇게나 곁에 있었는데 마치 거짓말 같아",
    },
    {
      timestamp: "3:15",
      original: "とても忘れられない　それだけが確か",
      hiragana: "とてもわすれられない　それだけがたしか",
      katakana: "トテモワスレラレナイ　ソレダケガタシカ",
      korean: "도저히 잊지 못하겠어 그것만이 확실해",
    },
    {
      timestamp: "3:31",
      original: "あの日の悲しみさえ　あの日の苦しみさえ",
      hiragana: "あのひのかなしみさえ　あのひのくるしみさえ",
      katakana: "アノヒノカナシミサエ　アノヒノクルシミサエ",
      korean: "그 날의 슬픔조차 그 날의 괴로움조차",
    },
    {
      timestamp: "3:37",
      original: "そのすべてを愛してた　あなたとともに",
      hiragana: "そのすべてをあいしてた　あなたとともに",
      katakana: "ソノスベテヲアイシテタ　アナタトトモニ",
      korean: "그 모든것을 사랑했던 당신과 함께",
    },
    {
      timestamp: "3:43",
      original: "胸に残り離れない　苦いレモンの匂い",
      hiragana: "むねにのこりはなれない　にがいれもんのにおい",
      katakana: "ムネニノコリハナレナイ　ニガイレモンノニオイ",
      korean: "가슴에 남아 떠나지 않는 씁쓸한 레몬 향기",
    },
    {
      timestamp: "3:48",
      original: "雨が降り止むまでは帰れない",
      hiragana: "あめがふりやむまではかえれない",
      katakana: "アメガフリヤムマデハカエレナイ",
      korean: "비가 그치기 전까지는 돌아갈 수 없어",
    },
    {
      timestamp: "3:54",
      original: "切り分けた果実の片方の様に",
      hiragana: "きりわけたかじつのかたほうのように",
      katakana: "キリワケタカジツノカタホウノヨウニ",
      korean: "잘라 나눈 과일의 한쪽 같이",
    },
    {
      timestamp: "4:00",
      original: "今でもあなたはわたしの光",
      hiragana: "いまでもあなたはわたしのひかり",
      katakana: "イマデモアナタハワタシノヒカリ",
      korean: "지금도 당신은 나의 빛",
    },
  ],
}

